### ISSUE TITLE
tcap2021DM.ipynb: Likelihood analysis error

### ISSUE THREAD

**Issue by monicava** [sergiohcdna/tcap2021DMTutorial#2]
I get the error below  in the likelihood step.

Where do I get the missing cntcube.fits file?

Thanks! Monica

like = ctools.ctlike(obssim.obs())

like.run()

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-dd43b63281a5> in <module>
      1 like = ctools.ctlike(obssim.obs())
----> 2 like.run()

~/opt/anaconda3/envs/ctathai/lib/python3.8/site-packages/ctools/tools.py in run(self)
   1852     def run(self):
   1853         """run(ctlike self)"""
-> 1854         return _tools.ctlike_run(self)
   1855 
   1856 

ValueError: *** ERROR in ctool::setup_observations(GObservations&): Invalid value. The "inobs" parameter "cntcube.fits" specifies a file that does not exist. Please specify  a valid event list, counts cube or  observation definition XML file.

Let's check the TS of the source

**Comment by sergiohcdna** [comment]
Hi Monica!

In the notebook, you need to run the simulation first. Please refer to the DM session today to check if you are running the simulation or not.

Cheers,
Sergio

**Comment by monicava** [comment]
Ok, I thought it was a complete notebook, not an unfinished one which will not run. Thanks!
